insert into public.stores (
  slug,
  name,
  short_description,
  seo_title,
  seo_description,
  suburb,
  state,
  address_line_1,
  postcode,
  phone,
  email,
  opening_hours,
  hero_heading,
  hero_text,
  is_active
)
values
  (
    'park-ridge',
    'Park Ridge',
    'Park Ridge store for repairs, pickup orders and accessories.',
    'TECHM8 Park Ridge',
    'Pickup and repair support from the Park Ridge TECHM8 store.',
    'Park Ridge',
    'QLD',
    'Shop 11, 3732 Mount Lindesay Hwy',
    '4125',
    '0452 488 710',
    'techm8.parkridge@gmail.com',
    'See store page for current trading hours',
    'TECHM8 Park Ridge',
    'Pickup, repairs and everyday tech support from Park Ridge.',
    true
  ),
  (
    'fairfield',
    'Fairfield',
    'Fairfield store for repairs, pickup orders and accessories.',
    'TECHM8 Fairfield',
    'Pickup and repair support from the Fairfield TECHM8 store.',
    'Fairfield',
    'QLD',
    'Shop 8, 180 Fairfield Rd',
    '4103',
    '0412 788 818',
    'techm8.fairfield@gmail.com',
    'See store page for current trading hours',
    'TECHM8 Fairfield',
    'Pickup, repairs and everyday tech support from Fairfield.',
    true
  ),
  (
    'toowong',
    'Toowong',
    'Toowong store for repairs, pickup orders and accessories.',
    'TECHM8 Toowong',
    'Pickup and repair support from the Toowong TECHM8 store.',
    'Toowong',
    'QLD',
    'Ground Level Shop 53, 9 Sherwood Rd',
    '4066',
    '0485 500 099',
    'techm8.toowong@gmail.com',
    'See store page for current trading hours',
    'TECHM8 Toowong',
    'Pickup, repairs and everyday tech support from Toowong.',
    true
  ),
  (
    'north-lakes',
    'North Lakes',
    'North Lakes store for repairs, pickup orders and accessories.',
    'TECHM8 North Lakes',
    'Pickup and repair support from the North Lakes TECHM8 store.',
    'North Lakes',
    'QLD',
    '1114A N Lakes Drive',
    '4509',
    '0482 390 009',
    'techm8.northlakes@gmail.com',
    'See store page for current trading hours',
    'TECHM8 North Lakes',
    'Pickup, repairs and everyday tech support from North Lakes.',
    true
  ),
  (
    'brassall',
    'Brassall',
    'Brassall store for repairs, pickup orders and accessories.',
    'TECHM8 Brassall',
    'Pickup and repair support from the Brassall TECHM8 store.',
    'Brassall',
    'QLD',
    '68 Hunter St, Primewest Brassall Shopping Centre',
    '4305',
    '0403 999 366',
    'techm8.brassall@gmail.com',
    'See store page for current trading hours',
    'TECHM8 Brassall',
    'Pickup, repairs and everyday tech support from Brassall.',
    true
  )
on conflict (slug) do update
set
  name = excluded.name,
  short_description = excluded.short_description,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  suburb = excluded.suburb,
  state = excluded.state,
  address_line_1 = excluded.address_line_1,
  postcode = excluded.postcode,
  phone = excluded.phone,
  email = excluded.email,
  opening_hours = excluded.opening_hours,
  hero_heading = excluded.hero_heading,
  hero_text = excluded.hero_text,
  is_active = excluded.is_active;
