alter table public.orders
  add column if not exists issuer_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists fulfillment_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists billing_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists amount_paid numeric(10,2) not null default 0,
  add column if not exists amount_refunded numeric(10,2) not null default 0,
  add column if not exists gst_amount numeric(10,2) not null default 0,
  add column if not exists paid_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists refunded_at timestamptz,
  add column if not exists cancel_reason text,
  add column if not exists stripe_customer_id text,
  add column if not exists confirmation_number text,
  add column if not exists confirmation_document_path text,
  add column if not exists invoice_number text,
  add column if not exists invoice_document_path text,
  add column if not exists invoice_issued_at timestamptz,
  add column if not exists packing_slip_path text,
  add column if not exists shipping_label_path text;

alter table public.orders
  drop constraint if exists orders_payment_status_check;

alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in (
    'unpaid',
    'pending',
    'paid',
    'failed',
    'partially_refunded',
    'refunded',
    'not_required'
  ));

alter table public.orders
  drop constraint if exists orders_amount_paid_nonnegative,
  drop constraint if exists orders_amount_refunded_nonnegative,
  drop constraint if exists orders_gst_amount_nonnegative;

alter table public.orders
  add constraint orders_amount_paid_nonnegative check (amount_paid >= 0),
  add constraint orders_amount_refunded_nonnegative check (amount_refunded >= 0),
  add constraint orders_gst_amount_nonnegative check (gst_amount >= 0);

update public.orders
set
  payment_status = 'unpaid',
  updated_at = timezone('utc', now())
where payment_method_code = 'pay_in_store'
  and payment_status = 'not_required';

update public.orders
set
  amount_paid = total_amount,
  paid_at = coalesce(paid_at, updated_at, created_at)
where payment_status in ('paid', 'partially_refunded', 'refunded')
  and amount_paid = 0;

update public.orders as orders
set issuer_snapshot = jsonb_strip_nulls(jsonb_build_object(
  'slug', issuer.slug,
  'name', issuer.name,
  'email', issuer.email,
  'phone', issuer.phone,
  'address_line_1', issuer.address_line_1,
  'address_line_2', issuer.address_line_2,
  'suburb', issuer.suburb,
  'state', issuer.state,
  'postcode', issuer.postcode,
  'country_code', 'AU'
))
from public.stores as issuer
where issuer.slug = case
  when orders.fulfillment_method = 'shipping' then 'park-ridge'
  else orders.store_slug
end
  and orders.issuer_snapshot = '{}'::jsonb;

update public.orders as orders
set fulfillment_snapshot = case
  when orders.fulfillment_method = 'shipping' then jsonb_strip_nulls(jsonb_build_object(
    'method', 'shipping',
    'recipient_name', orders.recipient_name,
    'company_name', orders.company_name,
    'phone', orders.shipping_phone,
    'email', orders.shipping_email,
    'address_line_1', orders.address_line_1,
    'address_line_2', orders.address_line_2,
    'suburb', orders.suburb,
    'state', orders.state,
    'postcode', orders.postcode,
    'country_code', orders.country_code
  ))
  else jsonb_strip_nulls(jsonb_build_object(
    'method', 'pickup',
    'slug', pickup.slug,
    'name', pickup.name,
    'email', pickup.email,
    'phone', pickup.phone,
    'address_line_1', pickup.address_line_1,
    'address_line_2', pickup.address_line_2,
    'suburb', pickup.suburb,
    'state', pickup.state,
    'postcode', pickup.postcode,
    'country_code', 'AU'
  ))
end
from public.stores as pickup
where pickup.slug = orders.store_slug
  and orders.fulfillment_snapshot = '{}'::jsonb;

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_key text not null,
  event_type text not null,
  title text not null,
  description text,
  actor_type text not null default 'system'
    check (actor_type in ('system', 'customer', 'admin', 'stripe')),
  actor_identifier text,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (order_id, event_key)
);

create table if not exists public.order_notifications (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_key text not null,
  recipient_role text not null
    check (recipient_role in ('customer', 'store', 'central')),
  recipient_email text not null,
  subject text not null,
  provider text not null default 'resend',
  provider_message_id text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed', 'skipped')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text,
  notification_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  sent_at timestamptz,
  unique (order_id, event_key, recipient_email)
);

create table if not exists public.order_documents (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  document_type text not null check (document_type in (
    'order_confirmation',
    'invoice',
    'credit_note',
    'packing_slip',
    'shipping_label',
    'pickup_label'
  )),
  source_ref text not null default '',
  document_number text,
  title text not null,
  status text not null default 'generating'
    check (status in ('generating', 'ready', 'failed', 'void')),
  storage_bucket text not null default 'order-documents',
  storage_path text,
  file_name text,
  mime_type text not null default 'application/pdf',
  document_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  issued_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (order_id, document_type, source_ref)
);

create table if not exists public.order_refunds (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  stripe_refund_id text unique,
  amount numeric(10,2) not null check (amount > 0),
  currency text not null default 'AUD',
  reason text,
  status text not null default 'pending'
    check (status in ('pending', 'succeeded', 'failed', 'cancelled')),
  requested_by text,
  provider_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz
);

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'processing'
    check (status in ('processing', 'processed', 'failed')),
  attempt_count integer not null default 1 check (attempt_count > 0),
  last_error text,
  received_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz
);

create index if not exists idx_order_events_order_created
  on public.order_events (order_id, created_at desc);
create index if not exists idx_order_notifications_order_created
  on public.order_notifications (order_id, created_at desc);
create index if not exists idx_order_notifications_retry
  on public.order_notifications (status, updated_at)
  where status in ('pending', 'failed');
create index if not exists idx_order_documents_order_created
  on public.order_documents (order_id, created_at desc);
create index if not exists idx_order_refunds_order_created
  on public.order_refunds (order_id, created_at desc);

alter table public.order_events enable row level security;
alter table public.order_notifications enable row level security;
alter table public.order_documents enable row level security;
alter table public.order_refunds enable row level security;
alter table public.stripe_webhook_events enable row level security;

revoke all on table public.order_events from anon, authenticated;
revoke all on table public.order_notifications from anon, authenticated;
revoke all on table public.order_documents from anon, authenticated;
revoke all on table public.order_refunds from anon, authenticated;
revoke all on table public.stripe_webhook_events from anon, authenticated;

drop trigger if exists set_updated_at_order_notifications on public.order_notifications;
create trigger set_updated_at_order_notifications
before update on public.order_notifications
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_order_documents on public.order_documents;
create trigger set_updated_at_order_documents
before update on public.order_documents
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_order_refunds on public.order_refunds;
create trigger set_updated_at_order_refunds
before update on public.order_refunds
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_stripe_webhook_events on public.stripe_webhook_events;
create trigger set_updated_at_stripe_webhook_events
before update on public.stripe_webhook_events
for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('order-documents', 'order-documents', false, 10485760, array['application/pdf'])
on conflict (id) do update
set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.order_events is
  'Immutable order activity timeline used by admin order details.';
comment on table public.order_notifications is
  'Idempotent three-party order email delivery log and retry state.';
comment on table public.order_documents is
  'Private generated order confirmations, invoices, credit notes, packing slips and labels.';
comment on table public.order_refunds is
  'Stripe-backed refund ledger. Order payment state is derived from succeeded rows.';

-- Harden pre-existing helper/trigger functions reported by the database advisor.
-- Trigger execution is unaffected; these SECURITY DEFINER functions are not public RPCs.
do $$
declare
  function_ref regprocedure;
begin
  foreach function_ref in array array[
    to_regprocedure('public.set_updated_at()'),
    to_regprocedure('public.normalize_customer_contact_email(text)'),
    to_regprocedure('public.normalize_customer_contact_phone(text)'),
    to_regprocedure('public.customer_contact_key_for_submission(text,text)'),
    to_regprocedure('public.merge_customer_contact_labels(text,text)')
  ]
  loop
    if function_ref is not null then
      execute format(
        'alter function %s set search_path = pg_catalog, public',
        function_ref
      );
    end if;
  end loop;

  foreach function_ref in array array[
    to_regprocedure('public.handle_new_user()'),
    to_regprocedure('public.sync_customer_contact_from_order()'),
    to_regprocedure('public.sync_customer_contact_from_repair_booking()'),
    to_regprocedure('public.upsert_customer_contact_from_submission(text,bigint,text,text,text,text,uuid,text,text,timestamptz,jsonb)')
  ]
  loop
    if function_ref is not null then
      execute format(
        'revoke execute on function %s from public, anon, authenticated',
        function_ref
      );
    end if;
  end loop;
end
$$;
