create table if not exists public.payment_fee_profiles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  provider text not null default 'manual',
  fee_type text not null check (fee_type in ('none', 'fixed', 'percent', 'combined')),
  percentage numeric(6,3) not null default 0,
  fixed_amount numeric(10,2) not null default 0,
  is_enabled boolean not null default true,
  sort_order integer not null default 0,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  customer_name text not null,
  phone text not null,
  email text not null,
  preferred_contact_method text not null default 'phone' check (preferred_contact_method in ('phone', 'email', 'sms')),
  store_id bigint references public.stores(id),
  store_slug text not null,
  fulfillment_method text not null default 'pickup' check (fulfillment_method in ('pickup', 'shipping')),
  recipient_name text,
  company_name text,
  shipping_phone text,
  shipping_email text,
  address_line_1 text,
  address_line_2 text,
  suburb text,
  state text,
  postcode text,
  country_code text not null default 'AU',
  notes text,
  currency text not null default 'AUD',
  subtotal_amount numeric(10,2) not null default 0,
  discount_amount numeric(10,2) not null default 0,
  payment_fee_amount numeric(10,2) not null default 0,
  shipping_fee_amount numeric(10,2) not null default 0,
  total_amount numeric(10,2) not null default 0,
  payment_fee_profile_id bigint references public.payment_fee_profiles(id),
  payment_method_code text,
  payment_method_label text,
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'pending', 'paid', 'failed', 'refunded', 'not_required')),
  status text not null default 'submitted' check (status in ('draft', 'submitted', 'confirmed', 'packed', 'shipped', 'completed', 'cancelled')),
  fulfillment_status text not null default 'new' check (fulfillment_status in ('new', 'queued', 'ready_for_pickup', 'packed', 'label_created', 'shipped', 'completed', 'cancelled')),
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  shipping_provider text,
  shipping_service_code text,
  shipping_service_name text,
  shipping_reference text,
  tracking_number text,
  tracking_url text,
  shipping_label_url text,
  packing_slip_url text,
  source text not null default 'website',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  sku text,
  product_slug text,
  product_name text not null,
  brand text,
  category_name text,
  compatibility text,
  image_url text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null default 0,
  compare_at_price numeric(10,2),
  line_total numeric(10,2) not null default 0,
  product_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null,
  service_code text,
  service_name text,
  shipment_id text,
  article_id text,
  label_format text,
  label_url text,
  manifest_url text,
  tracking_number text,
  tracking_url text,
  status text not null default 'pending' check (status in ('pending', 'label_created', 'lodged', 'shipped', 'delivered', 'cancelled', 'failed')),
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_store_created on public.orders (store_slug, created_at desc);
create index if not exists idx_orders_status on public.orders (status, payment_status, fulfillment_status);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_shipments_order_id on public.shipments (order_id);

alter table public.payment_fee_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;

drop policy if exists "public can read enabled payment fee profiles" on public.payment_fee_profiles;
create policy "public can read enabled payment fee profiles"
on public.payment_fee_profiles
for select
to anon, authenticated
using (is_enabled = true);

drop trigger if exists set_updated_at_payment_fee_profiles on public.payment_fee_profiles;
create trigger set_updated_at_payment_fee_profiles
before update on public.payment_fee_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_orders on public.orders;
create trigger set_updated_at_orders
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_shipments on public.shipments;
create trigger set_updated_at_shipments
before update on public.shipments
for each row execute function public.set_updated_at();

insert into public.payment_fee_profiles (
  code,
  label,
  provider,
  fee_type,
  percentage,
  fixed_amount,
  is_enabled,
  sort_order,
  notes
)
values
  ('pay_in_store', 'Pay in store', 'manual', 'none', 0, 0, true, 10, 'Used for order requests that will be paid in-store.'),
  ('card', 'Card', 'stripe', 'combined', 1.700, 0.30, true, 20, 'Base domestic card fee placeholder. Review against your actual Stripe statement before going live.'),
  ('apple_pay', 'Apple Pay', 'stripe', 'combined', 1.700, 0.30, true, 30, 'Apple Pay on Stripe uses card rails, so pricing normally matches the underlying card fee.'),
  ('afterpay_clearpay', 'Afterpay', 'stripe', 'combined', 5.490, 0.30, true, 40, 'Starter placeholder based on standard AU BNPL pricing. Confirm before charging customers.'),
  ('wechat_pay', 'WeChat Pay', 'stripe', 'none', 0, 0, false, 50, 'Enable only after confirming your Stripe account can use WeChat Pay and after setting your actual cost recovery rule.'),
  ('paypal', 'PayPal', 'external', 'none', 0, 0, false, 60, 'Disabled by default. Confirm PayPal availability for your Stripe account or connect PayPal directly before enabling.')
on conflict (code) do update
set
  label = excluded.label,
  provider = excluded.provider,
  fee_type = excluded.fee_type,
  percentage = excluded.percentage,
  fixed_amount = excluded.fixed_amount,
  is_enabled = excluded.is_enabled,
  sort_order = excluded.sort_order,
  notes = excluded.notes;
