create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'staff' check (role in ('super_admin', 'store_manager', 'staff')),
  store_slug text references public.stores(slug) on update cascade on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists admin_users_email_unique_idx
on public.admin_users (lower(email))
where email is not null;

create index if not exists idx_admin_users_role_store
on public.admin_users (role, store_slug, is_active);

alter table public.admin_users enable row level security;

drop trigger if exists set_updated_at_admin_users on public.admin_users;
create trigger set_updated_at_admin_users
before update on public.admin_users
for each row execute function public.set_updated_at();

comment on table public.admin_users is 'Back-office admin whitelist and role mapping for the TECHM8 admin panel.';

comment on column public.admin_users.role is 'super_admin can manage everything, store_manager is scoped to one store, staff is read/update within scope.';

-- Example first admin record:
-- insert into public.admin_users (auth_user_id, email, display_name, role, store_slug, is_active)
-- values ('replace-with-auth-user-uuid', 'owner@example.com', 'TECHM8 Owner', 'super_admin', null, true);
