create extension if not exists pgcrypto;

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  short_description text,
  seo_title text,
  seo_description text,
  suburb text,
  state text,
  address_line_1 text,
  address_line_2 text,
  postcode text,
  phone text,
  email text,
  opening_hours text,
  hero_heading text,
  hero_text text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_name text,
  email text,
  phone text,
  website_url text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  slug text not null unique,
  name text not null,
  brand text,
  model text,
  category_id bigint references public.categories(id),
  supplier_id bigint references public.suppliers(id),
  short_description text,
  description text,
  condition_label text,
  compatibility text,
  cost_price numeric(10,2),
  wholesale_price numeric(10,2),
  retail_price numeric(10,2),
  compare_at_price numeric(10,2),
  image_url text,
  supplier_image_url text,
  supplier_product_url text,
  stock_quantity integer not null default 0,
  min_order_quantity integer not null default 1,
  is_featured boolean not null default false,
  is_visible boolean not null default true,
  seo_title text,
  seo_description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.product_store_inventory (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  quantity integer not null default 0,
  shelf_location text,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (product_id, store_id)
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  source_name text,
  source_url text,
  old_cost_price numeric(10,2),
  new_cost_price numeric(10,2),
  old_wholesale_price numeric(10,2),
  new_wholesale_price numeric(10,2),
  old_retail_price numeric(10,2),
  new_retail_price numeric(10,2),
  changed_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.repair_bookings (
  id bigint generated by default as identity primary key,
  booking_code text not null unique,
  store_slug text not null,
  repair_category text not null check (repair_category in ('phone', 'computer', 'tablet', 'gaming_console')),
  brand text,
  device_model text not null,
  issue_description text not null,
  preferred_date date,
  preferred_time text,
  customer_name text not null,
  phone text not null,
  email text not null,
  preferred_contact_method text not null default 'phone' check (preferred_contact_method in ('phone', 'email', 'sms')),
  status text not null default 'new' check (status in ('new', 'contacted', 'in_progress', 'completed', 'cancelled')),
  admin_notes text,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_repair_bookings_store_status on public.repair_bookings (store_slug, status);
create index if not exists idx_repair_bookings_created_at on public.repair_bookings (created_at desc);

alter table public.stores enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_store_inventory enable row level security;
alter table public.price_history enable row level security;
alter table public.repair_bookings enable row level security;
alter table public.suppliers enable row level security;

drop policy if exists "public can read active stores" on public.stores;
create policy "public can read active stores"
on public.stores
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories"
on public.categories
for select
to anon, authenticated
using (true);

drop policy if exists "public can read visible products" on public.products;
create policy "public can read visible products"
on public.products
for select
to anon, authenticated
using (is_visible = true);

drop policy if exists "public can read product images" on public.product_images;
create policy "public can read product images"
on public.product_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.is_visible = true
  )
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_updated_at_stores on public.stores;
create trigger set_updated_at_stores
before update on public.stores
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_categories on public.categories;
create trigger set_updated_at_categories
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_suppliers on public.suppliers;
create trigger set_updated_at_suppliers
before update on public.suppliers
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_products on public.products;
create trigger set_updated_at_products
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_repair_bookings on public.repair_bookings;
create trigger set_updated_at_repair_bookings
before update on public.repair_bookings
for each row execute function public.set_updated_at();

