-- Careers / job application intake.
--
-- Applications arrive from the public /careers page through the
-- `submit-job-application` Edge Function, which writes with the service role.
-- No anon or authenticated policy is granted, matching public.repair_bookings:
-- applicant records contain personal data and work-eligibility details and must
-- never be readable from the browser.

create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  reference_code text not null unique,
  store_slug text not null,
  role_interest text[] not null default '{}',
  employment_type text not null check (employment_type in ('casual', 'part_time', 'full_time', 'any')),
  availability text[] not null default '{}',
  earliest_start text,

  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  suburb text,
  postcode text,

  -- Australian work eligibility. `work_rights` is the applicant's declared
  -- status; the visa columns are only populated for temporary visa holders.
  work_rights text not null,
  visa_subclass text,
  visa_expiry date,
  work_hours_limit text,

  -- Rostering depends on whether an applicant can reliably reach the store.
  own_transport text not null,
  drivers_licence text not null,

  experience_summary text,

  resume_path text,
  resume_filename text,
  resume_mime_type text,
  resume_size_bytes integer,

  -- Which poster / QR code / channel the application came from.
  source text,

  status text not null default 'new' check (status in ('new', 'reviewing', 'shortlisted', 'interviewed', 'hired', 'declined')),
  admin_notes text,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_job_applications_store_status
  on public.job_applications (store_slug, status);
create index if not exists idx_job_applications_created_at
  on public.job_applications (created_at desc);
create index if not exists idx_job_applications_email
  on public.job_applications (lower(email));

alter table public.job_applications enable row level security;

drop trigger if exists set_updated_at_job_applications on public.job_applications;
create trigger set_updated_at_job_applications
before update on public.job_applications
for each row execute function public.set_updated_at();

-- Private resume bucket. 5 MB matches the client-side upload guard on
-- /careers.html; the MIME allow-list keeps the bucket to document formats only.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'job-applications',
  'job-applications',
  false,
  5242880,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/rtf',
    'text/plain'
  ]
)
on conflict (id) do update
set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.job_applications is
  'Public careers page applications. Written by the submit-job-application Edge Function with the service role; resumes live in the private job-applications storage bucket.';
comment on column public.job_applications.work_rights is
  'Declared Australian work eligibility, e.g. australian_citizen, permanent_resident, student_500.';
comment on column public.job_applications.resume_path is
  'Object path inside the private job-applications storage bucket.';
comment on column public.job_applications.source is
  'Acquisition channel, e.g. poster QR scan in a specific store.';
